In [1]:
import numpy as np

In [2]:
arr_1d=np.array([1,2,3,4,5])

In [3]:
print(arr_1d)

[1 2 3 4 5]


In [4]:
type(arr_1d)#datatype function of python

numpy.ndarray

In [5]:
arr_1d.ndim#dimension of array


1

In [6]:
arr_2d=([[11,12,13],[21,22,23]])
print(arr_2d)

[[11, 12, 13], [21, 22, 23]]


In [8]:
arr_2d=np.array([[11,12,13],[21,22,23]])
print(arr_2d)

[[11 12 13]
 [21 22 23]]


In [9]:
type(arr_2d)

numpy.ndarray

In [10]:
arr_2d.ndim

2

In [11]:
arr_2d.size

6

In [12]:
arr_2d.shape


(2, 3)

In [13]:
#(row,col)

In [14]:
arr_2d.dtype

dtype('int32')

In [15]:
arr_2d

array([[11, 12, 13],
       [21, 22, 23]])