In [1]:
import numpy as np

In [2]:
mat=np.array([[1,1,1],[2,2,2],[3,3,3]])
print(mat)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [3]:
mx_1s=np.ones(5)#1d array
print(mx_1s)

[1. 1. 1. 1. 1.]


In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [5]:
mx_1s.dtype #float by default

dtype('float64')

In [6]:
mx1_1s=np.ones((3,4)) #rows,col
print(mx1_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
mx2_1s=np.ones((3,4),dtype=int)#shift+tab for more info by bringing cursor within parenthesis
print(mx2_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [15]:
mx_0s=np.zeros((5,7),dtype=bool)
print(mx_0s)

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]]


In [16]:
mx_0s=np.zeros((5,7),dtype=str)
print(mx_0s)

[['' '' '' '' '' '' '']
 ['' '' '' '' '' '' '']
 ['' '' '' '' '' '' '']
 ['' '' '' '' '' '' '']
 ['' '' '' '' '' '' '']]


In [17]:
em_str=""
print(bool(em_str))

False


In [21]:
mx_em=np.empty((2,4))#random value
print(mx_em)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 8.55721699e-321 1.37959740e-306 2.29175545e-312]]
