# NUMPY FUNC()

In [1]:
import numpy as np


# ARANGE()


In [2]:
ar_1d=np.arange(1,13)#13 not included
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
ar1_1ds=np.arange(1,13)
print(ar1_1ds)
ar1_1d=np.arange(1,13,2)#start,end,steps oskip in between
print(ar1_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  3  5  7  9 11]


# LINSPACE()

In [4]:
arr_1d=np.linspace(1,5,3)#start,end,how many total element
print(arr_1d)
arr_1sd=np.linspace(1,6,7)
print(arr_1sd)

[1. 3. 5.]
[1.         1.83333333 2.66666667 3.5        4.33333333 5.16666667
 6.        ]


# RESHAPE()

In [6]:
ar_2d=ar_1d.reshape(6,2)#row,column
print(ar_2d)
ar_3d=ar_1d.reshape(2,3,2)
print(ar_3d)
ar_3d=ar_1d.reshape(3,1,4)#3 compartments of 1 row and 4 columns
print(ar_3d)
ar3=np.arange(1,15).reshape(2,7)
print(ar3)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


# ravel()

In [7]:
#multidimensional array in 1d
ar3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# flatten()

In [18]:
ar3.flatten() #bring pointer between parenthesis and press shift+tab

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# transpose

In [19]:
ar3.transpose()#initially 2 rows 7columns = now, 7 rows and 2 columns

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13],
       [ 7, 14]])

In [20]:
ar3.T

array([[ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 4, 11],
       [ 5, 12],
       [ 6, 13],
       [ 7, 14]])